/*
 * Characteristics of floating types.
 */

#pragma once

/* Use definitions generated by GCC / clang */

#define DBL_DECIMAL_DIG     10
#define DBL_DIG             10
#define DBL_EPSILON
#define DBL_HAS_SUBNORM
#define DBL_MANT_DIG
#define DBL_MAX
#define DBL_MAX_10_EXP
#define DBL_MAX_EXP
#define DBL_MIN
#define DBL_MIN_10_EXP
#define DBL_MIN_EXP
#define DBL_TRUE_MIN
#define DECIMAL_DIG
#define FLT_DECIMAL_DIG
#define FLT_DIG
#define FLT_EPSILON
#define FLT_EVAL_METHOD
#define FLT_HAS_SUBNORM
#define FLT_MANT_DIG
#define FLT_MAX
#define FLT_MAX_10_EXP
#define FLT_MAX_EXP
#define FLT_MIN
#define FLT_MIN_10_EXP
#define FLT_MIN_EXP
#define FLT_RADIX
#define FLT_ROUNDS
#define FLT_TRUE_MIN
#define LDBL_DECIMAL_DIG
#define LDBL_DIG
#define LDBL_EPSILON
#define LDBL_HAS_SUBNORM
#define LDBL_MANT_DIG
#define LDBL_MAX
#define LDBL_MAX_10_EXP
#define LDBL_MAX_EXP
#define LDBL_MIN
#define LDBL_MIN_10_EXP
#define LDBL_MIN_EXP
#define LDBL_TRUE_MIN
