/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

/*
 * ISO/IEC 9899:2018 7.10 - Sizes of integer types
 */

#pragma once

/* Use definitions generated by GCC / clang */

#define CHAR_BIT    __CHAR_BIT__
#if __CHAR_UNSIGNED__
#define CHAR_MAX    UCHAR_MAX
#define CHAR_MIN    0
#else
#define CHAR_MAX    SCHAR_MAX
#define CHAR_MIN    SCHAR_MIN
#endif
#define SHRT_MAX    __SHRT_MAX__
#define SHRT_MIN    ((-__SHRT_MAX__) - 1)
#define INT_MAX     __INT_MAX__
#define INT_MIN     ((-__INT_MAX__) - 1)
#define LONG_MAX    __LONG_MAX__
#define LONG_MIN    ((-__LONG_MAX__) - 1)
#define LLONG_MAX   __LLONG_MAX__
#define LLONG_MIN   ((-__LLONG_MAX__) - 1)
/* We don't support multibyte characters in libcore */
#define SCHAR_MAX   __SCHAR_MAX__
#define SCHAR_MIN   ((-__SCHAR_MAX__) - 1)
#define UCHAR_MAX   (__SCHAR_MAX__ + 1 + __SCHAR_MAX__)
#define USHRT_MAX   (__SHRT_MAX__ + 1 + __SHRT_MAX__)
#define UINT_MAX    (__INT_MAX__ + 1 + __INT_MAX__)
#define ULONG_MAX   (__LONG_MAX__ + 1 + __LONG_MAX__)
#define ULLONG_MAX  (__LLONG_MAX__ + 1 + __LLONG_MAX__)
